version: '3.8'

# Configuración de desarrollo que extiende docker-compose.yml
services:
  afip-api:
    environment:
      # Configuración de desarrollo
      - PHP_ENV=development
      - LOG_LEVEL=debug
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
      
    volumes:
      # Montar código fuente para desarrollo en vivo
      - .:/app:delegated
      - /app/vendor  # Mantener vendor del contenedor
      - /app/data    # Mantener data persistente
      
      # Logs en vivo para desarrollo
      - ./logs:/app/logs
      
    ports:
      # Puerto adicional para Xdebug
      - "9003:9003"
      
    command: >
      bash -c "
        echo 'Iniciando en modo desarrollo...' &&
        composer install --dev &&
        apache2-foreground
      "

# Servicios adicionales para desarrollo
  mailhog:
    image: mailhog/mailhog:latest
    container_name: afip-api-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - afip-network

  adminer:
    image: adminer:latest
    container_name: afip-api-adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=database
    networks:
      - afip-network
    profiles:
      - tools 